FROM python:3.9-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --index-url http://devpi-helm-devpi:3141/root/pypi/+simple/ \
                --trusted-host devpi-helm-devpi \
                --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.9-slim

WORKDIR /app

RUN groupadd -g 3000 app && useradd -m -u 10001 -g 3000 --no-log-init app

COPY --from=builder /install /usr/local

COPY src /app/src

ENV PYTHONPATH=/app/src

USER app

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]